# Generated by Django 4.1.4 on 2022-12-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cooking_time', models.PositiveIntegerField(help_text='in minutes')),
                ('ingredients', models.CharField(max_length=250)),
                ('difficulty', models.CharField(max_length=20)),
            ],
        ),
    ]
